% Copyright (c) 2018 Adanay Martín & Oliver Schütze.
% This file is subject to the terms and conditions defined in
% the file 'LICENSE.txt', which is part of this source code package.

function [result, stats] = minfinit(it1, stats)
% Initializes and fill the structures for the output of a minimization algorithm. 

result = struct(...
  'x', it1.x,...
  'fx', it1.fx,...
  'Jx', it1.Jx,...
  'Hx', it1.Hx,...
  'Hident', it1.Hident,...
  'Lx', it1.Lx,...
  'Lmodif', it1.Lmodif,...
  'ax', it1.ax,...
  'aeqx', it1.aeqx,...
  'cx', it1.cx,...
  'Jcx', it1.Jcx,...
  'Hcx', it1.Hcx,...
  'ceqx', it1.ceqx,...
  'Jceqx', it1.Jceqx,...
  'Hceqx', it1.Hceqx,...
  'dceqx', it1.dceqx,... % square norm of the equalities
  'dcx', it1.dcx,... % square norm of the inequalities
  'v', it1.v,...
  'd', it1.d,... % measure of the objectives decrease
  't', it1.t,...
  'w', it1.w,...
  'FirstOrdOpt', it1.FirstOrdOpt);
    
if stats.OptIts > 0
  stats.OptDirIts = stats.OptDirIts / stats.OptIts;
  stats.OptLsIts = stats.OptLsIts / stats.OptIts;
end
end

