function [stats] = minstats()
% Initializes an optimization method statistics structure.

% Copyright (c) 2018 Adanay Martín & Oliver Schütze.
% This file is subject to the terms and conditions defined in
% the file 'LICENSE.txt', which is part of this source code package.

stats = struct(...
  'OptIts', 0,...
  'OptDirIts', 0,...
  'OptLsIts', 0,...
  'fCount', 0,...
  'JCount', 0,...
  'HCount', 0,...
  'JvCount', 0, 'wJCount', 0, 'wJvCount', 0, 'vHCount', 0, 'HwCount', 0, 'HwvCount', 0,...
  'aCount', 0,...
  'aeqCount', 0,...
  'cCount', 0,...
  'JcCount', 0,...
  'HcCount', 0,...
  'JcvCount', 0, 'wJcCount', 0, 'wJcvCount', 0, 'vHcCount', 0, 'HcwCount', 0, 'HcwvCount', 0,...
  'ceqCount', 0,...
  'JceqCount', 0,...
  'HceqCount', 0,...
  'JceqvCount', 0, 'wJceqCount', 0, 'wJceqvCount', 0, 'vHceqCount', 0, 'HceqwCount', 0, 'HceqwvCount', 0);
end

